from __future__ import annotations

import os
from pathlib import Path
from typing import Iterable

SECRET_KEYS = {
    "IBM_QUANTUM_TOKEN",
    "AZURE_CLIENT_SECRET",
    "AZURE_QUANTUM_CONNECTION_STRING",
}

CONFIG_KEYS = (
    "IBM_QUANTUM_TOKEN",
    "IBM_QUANTUM_INSTANCE",
    "IBM_QUANTUM_BACKEND",
    "AZURE_TENANT_ID",
    "AZURE_CLIENT_ID",
    "AZURE_CLIENT_SECRET",
    "AZURE_SUBSCRIPTION_ID",
    "AZURE_QUANTUM_RESOURCE_GROUP",
    "AZURE_QUANTUM_WORKSPACE",
    "AZURE_QUANTUM_RESOURCE_ID",
    "AZURE_QUANTUM_TARGET",
    "AZURE_QUANTUM_CONNECTION_STRING",
)


def default_env_path() -> Path:
    return Path(os.getenv("QBT_ENV_FILE", ".env")).expanduser()


def _parse_env_line(line: str) -> tuple[str, str] | None:
    stripped = line.strip()
    if not stripped or stripped.startswith("#") or "=" not in stripped:
        return None
    key, value = stripped.split("=", 1)
    key = key.strip()
    value = value.strip()
    if not key:
        return None
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        value = value[1:-1]
    return key, value


def load_env_file(path: str | Path | None = None, *, override: bool = False) -> Path | None:
    """Load a simple local .env file without adding a runtime dependency.

    Existing process environment variables win unless ``override=True``.
    The file is intended for local development only and should remain gitignored.
    """
    env_path = Path(path).expanduser() if path is not None else default_env_path()
    if not env_path.exists():
        return None
    for line in env_path.read_text(encoding="utf-8").splitlines():
        parsed = _parse_env_line(line)
        if parsed is None:
            continue
        key, value = parsed
        if override or key not in os.environ:
            os.environ[key] = value
    return env_path


def write_env_file(
    values: dict[str, str],
    path: str | Path | None = None,
    *,
    overwrite: bool = False,
) -> Path:
    """Write/update a local .env file and restrict permissions where supported."""
    env_path = Path(path).expanduser() if path is not None else default_env_path()
    existing: dict[str, str] = {}
    if env_path.exists():
        for line in env_path.read_text(encoding="utf-8").splitlines():
            parsed = _parse_env_line(line)
            if parsed is None:
                continue
            key, value = parsed
            existing[key] = value

    for key, value in values.items():
        if key not in CONFIG_KEYS or value is None:
            continue
        if overwrite or not existing.get(key):
            existing[key] = value.strip()

    lines = [
        "# QBT local credentials/configuration. NEVER commit this file.",
        "# Generated by `qbt configure`.",
        "",
    ]
    for key in CONFIG_KEYS:
        if key in existing:
            lines.append(f"{key}={existing[key]}")
    env_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    try:
        env_path.chmod(0o600)
    except OSError:
        pass
    return env_path


def masked_value(value: str | None) -> str:
    return "configured" if value else "missing"


def config_status(keys: Iterable[str] = CONFIG_KEYS) -> dict[str, str]:
    load_env_file()
    out: dict[str, str] = {}
    for key in keys:
        value = os.getenv(key)
        out[key] = masked_value(value) if key in SECRET_KEYS else ("configured" if value else "missing")
    return out


def missing_for(provider: str) -> list[str]:
    """Return configuration that is definitely missing for a requested provider.

    IBM can also use a previously saved Qiskit Runtime account, so a missing token is
    advisory rather than proof that authentication will fail.
    Azure can use DefaultAzureCredential/CLI login; workspace identity is checked here.
    """
    load_env_file()
    provider = provider.lower()
    if provider == "ibm":
        return [] if os.getenv("IBM_QUANTUM_TOKEN") else ["IBM_QUANTUM_TOKEN or saved IBM account"]
    if provider == "azure":
        if os.getenv("AZURE_QUANTUM_CONNECTION_STRING"):
            return []
        if os.getenv("AZURE_QUANTUM_RESOURCE_ID"):
            return []
        trio = ["AZURE_SUBSCRIPTION_ID", "AZURE_QUANTUM_RESOURCE_GROUP", "AZURE_QUANTUM_WORKSPACE"]
        return [key for key in trio if not os.getenv(key)]
    return []
